name: Pipeline_Entrega_Impacta

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  exemplo:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v4

      - name: Chama_LogExecucao
        run: echo "Pipeline executado com sucesso mediante a aula explicativa Impacta!"
